
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 02 23:07:42 ICT 2019
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEPARATOR = 6;
  public static final int NUMBER = 9;
  public static final int BOOLEAN = 10;
  public static final int ASSIGNER = 5;
  public static final int VARIABLE = 7;
  public static final int EOF = 0;
  public static final int PRIM_STRING = 4;
  public static final int error = 1;
  public static final int PRIM_INTEGER = 2;
  public static final int TEXT = 8;
  public static final int PRIM_BOOLEAN = 3;
}

