
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 02 11:09:27 ICT 2019
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEPARATOR = 6;
  public static final int INTEGER = 2;
  public static final int NUMBER = 9;
  public static final int BOOLEAN = 3;
  public static final int ASSIGNER = 5;
  public static final int VARIABLE = 7;
  public static final int EOF = 0;
  public static final int STRING = 4;
  public static final int error = 1;
  public static final int TEXT = 8;
}

